//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMCINVENTORYSYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CABINET
    {
        public int CabinetID { get; set; }
        public string CabinetName { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> Responsible { get; set; }
    }
}
