//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMCINVENTORYSYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM_LOCATION
    {
        public int ItemLocationID { get; set; }
        public string StockNo { get; set; }
        public string ItemName { get; set; }
        public string MainNo { get; set; }
        public string DrawerNo { get; set; }
        public string BinNo { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
