//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMCINVENTORYSYSTEM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ItemLocationEntities : DbContext
    {
        public ItemLocationEntities()
            : base("name=ItemLocationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BIN> BINs { get; set; }
        public virtual DbSet<CABINET> CABINETs { get; set; }
        public virtual DbSet<DRAWER> DRAWERs { get; set; }
        public virtual DbSet<ITEM_LOCATION> ITEM_LOCATION { get; set; }
        public virtual DbSet<RACK> RACKs { get; set; }
    }
}
