//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMCINVENTORYSYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERMAINMENU
    {
        public USERMAINMENU()
        {
            this.USERSUBMENUs = new HashSet<USERSUBMENU>();
        }
    
        public int MainID { get; set; }
        public int MainAccessKey { get; set; }
        public string MainName { get; set; }
    
        public virtual ICollection<USERSUBMENU> USERSUBMENUs { get; set; }
    }
}
