//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GMCINVENTORYSYSTEM
{
    using System;
    using System.Collections.Generic;
    
    public partial class USERSUBMENU
    {
        public int SubID { get; set; }
        public int SubMainAccessKey { get; set; }
        public int SubAccessKey { get; set; }
        public string SubName { get; set; }
    
        public virtual USERMAINMENU USERMAINMENU { get; set; }
    }
}
